"""Added new owner column to note

Revision ID: 0f2a6810e7b2
Revises: 7bb8aef74eca
Create Date: 2024-04-11 17:54:59.029389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f2a6810e7b2'
down_revision: Union[str, None] = '7bb8aef74eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'content',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('note', 'content',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
